"""create_news_items_table

Revision ID: ed4c0fb7e03c
Revises: '6c293401b456'
Create Date: 2026-08-03 16:30:06.393008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed4c0fb7e03c'
down_revision: Union[str, None] = '6c293401b456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('matched_topics_json', sa.Text(), nullable=True),
    sa.Column('seen', sa.Boolean(), nullable=True),
    sa.Column('saved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_items_relevance_score'), 'news_items', ['relevance_score'], unique=False)
    op.create_index(op.f('ix_news_items_saved'), 'news_items', ['saved'], unique=False)
    op.create_index(op.f('ix_news_items_source'), 'news_items', ['source'], unique=False)
    op.create_index(op.f('ix_news_items_url'), 'news_items', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_index(op.f('ix_news_items_url'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_source'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_saved'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_relevance_score'), table_name='news_items')
    op.drop_table('news_items')
    # ### end Alembic commands ###
